---
roles:
  - name: RHEL9-STIG
    src: git@github.com:ansible-lockdown/RHEL9-STIG.git
    scm: git
    version: 2.2.0
  - name: RHEL9-CIS
    src: git@github.com:ansible-lockdown/RHEL9-CIS.git
    scm: git
    version: 2.0.0
