---
windows:
  hosts:
    windows_server1:
      ansible_host:
    windows_server2:
      ansible_host:

  vars:
    ansible_user: Administrator
    ansible_password: "admin"
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
